---
- name: Setting up environment before executing kernel optimization tests
  hosts: all
  tasks: 
    - name: Print all changes made in this setup scripts
      debug: 
        msg: "Setting up Default settings tests doesn't have any additional prerequisites"

    - name: Increase core read buffer size
      ansible.posix.sysctl: 
        name: net.core.rmem_max
        value: 16777216
        sysctl_file: /etc/sysctl.d/90_test.conf
        reload: true
        state: present

    - name: Increase core write buffer size
      ansible.posix.sysctl: 
        name: net.core.wmem_max
        value: 16777216
        sysctl_file: /etc/sysctl.d/90_test.conf
        reload: true
        state: present

    - name: Increase IPv4 TCP read buffer size
      ansible.posix.sysctl: 
        name: net.ipv4.tcp_rmem
        value: "4096 87380 16777216"
        sysctl_file: /etc/sysctl.d/90_test.conf
        reload: true
        state: present

    - name: Increase IPv4 TCP write buffer size
      ansible.posix.sysctl: 
        name: net.ipv4.tcp_wmem
        value: "4096 87380 16777216"
        sysctl_file: /etc/sysctl.d/90_test.conf
        reload: true
        state: present

    - name: Enable TCP window scaling
      ansible.posix.sysctl: 
        name: net.ipv4.tcp_window_scaling
        value: 1
        sysctl_file: /etc/sysctl.d/90_test.conf
        reload: true
        state: present

    - name: Enable TCP timestamps
      ansible.posix.sysctl: 
        name: net.ipv4.tcp_timestamps
        value: 1
        sysctl_file: /etc/sysctl.d/90_test.conf
        reload: true
        state: present

    - name: Enable TCP selective acknowledgement
      ansible.posix.sysctl: 
        name: net.ipv4.tcp_sack
        value: 1
        sysctl_file: /etc/sysctl.d/90_test.conf
        reload: true
        state: present

    - name: Increase number of file handles
      ansible.posix.sysctl: 
        name: fs.file-max
        value: 2097152
        sysctl_file: /etc/sysctl.d/90_test.conf
        reload: true
        state: present
      
    - name: Enable TCP fast open
      ansible.posix.sysctl: 
        name: net.ipv4.tcp_fastopen
        value: 3
        sysctl_file: /etc/sysctl.d/90_test.conf
        reload: true
        state: present
      
    - name: Reduce TCP FIN timeout
      ansible.posix.sysctl: 
        name: net.ipv4.tcp_fin_timeout
        value: 20
        sysctl_file: /etc/sysctl.d/90_test.conf
        reload: true
        state: present

    - name: Increase max TCP SYN backlog
      ansible.posix.sysctl: 
        name: net.ipv4.tcp_max_syn_backlog
        value: 4096
        sysctl_file: /etc/sysctl.d/90_test.conf
        reload: true
        state: present

    - name: Increase max TCP tw buckets
      ansible.posix.sysctl: 
        name: net.ipv4.tcp_max_tw_buckets
        value: 2000000
        sysctl_file: /etc/sysctl.d/90_test.conf
        reload: true
        state: present

    - name: Increase max TCP tw buckets
      ansible.posix.sysctl: 
        name: net.core.netdev_max_backlog
        value: 2000
        sysctl_file: /etc/sysctl.d/90_test.conf
        reload: true
        state: present

        