---
- name: Setup IP configuration for Default settings test (10 gigabit)
  hosts: doktnet01
  vars: 
    netplan_configuration: 
      ethernets: 
        ens2f0: 
          addresses: 
            - 172.16.21.{{ local_host_id }}/24
  tasks: 
    - name: Setup IP configuration on eno2 interface
      template: 
        src: ../../templates/netplan.cfg.j2
        mode: 0600
        dest: /etc/netplan/test.yaml
      tags: [setup-config]

    - name: Reload interface configuration 
      shell: "sudo netplan apply"
      ignore_errors: true
      tags: [apply-config]

- name: Setup IP configuration for Default settings test (10 gigabit)
  hosts: doktnet02
  vars: 
    netplan_configuration: 
      ethernets: 
        ens1f0: 
          addresses: 
            - 172.16.21.{{ local_host_id }}/24
  tasks: 
    - name: Setup IP configuration on eno2 interface
      template: 
        src: ../../templates/netplan.cfg.j2
        mode: 0600
        dest: /etc/netplan/test.yaml
      tags: [setup-config]

    - name: Reload interface configuration 
      shell: "sudo netplan apply"
      ignore_errors: true
      tags: [apply-config]

    - include_tasks: "../run_iperf_server.yml"
      vars:
        test_env: "{{ test_environment }}"
        kubeconfig: "../../kubeconfig"
      tags: ['setup-iperf']

    - include_tasks: "../run_netperf_server.yml"
      vars:
        test_env: "{{ test_environment }}"
        kubeconfig: "../../kubeconfig"
      tags: ['setup-netperf']

- name: Testing bandwith and latency for Default settings optimization level
  hosts: doktnet01
  vars_files: 
    - vars.yml
  tasks:
    - name: Create directory for storing tests
      file: 
        path: "{{ results_dir }}/{{ test_optimization }}/{{ test_configuration }}/{{ item }}"
        state: directory
        recurse: true
        owner: matej
        mode: 0775
      with_items: 
        - "bandwith"
        - "latency"
      tags: [setup-directory]
      when: ansible_hostname == "doktnet01"
      
    - name: Set MTU
      shell: "sudo ip link set dev {{ item }} mtu 1500"
      with_items: 
        - "{{ test_devices }}"
      ignore_errors: true
      tags: ['set-mtu']

    - include_tasks: "../../tests/test_bandwith.yml"
      vars: 
        test_endpoint: "{{ bandwidth_server }}"
        test_config: "{{ test_configuration }}"
        test_optim: "{{ test_optimization }}"
        test_port: "30080"
        test_packet_size: "{{ item[1] }}"
        test_duration: "30"
        test_log_output: "/testing_results/{{ test_optimization }}/{{ test_configuration }}/bandwith/{{ test_protocol }}-mtu-{{ test_mtu }}-packet-{{ test_packet_size }}-{{ item[0] }}.log"
        test_mtu: "1500"
        test_hostname: "doktnet01"
        test_protocol: "{{ item[2] }}"
        test_env: "{{ test_environment }}"
        kubeconfig: "../../kubeconfig"
      with_nested: 
        - "{{ range(1,3) }}"
        - "{{ packet_sizes }}"
        - "{{ protocols }}"
      tags: ['test-bandwith','mtu-1500']

    - include_tasks: "../../tests/test_latency.yml"
      vars: 
        test_endpoint: "{{ latency_server }}"
        test_config: "{{ test_configuration }}"
        test_optim: "{{ test_optimization }}"
        test_duration: "30"
        test_log_output: "/testing_results/{{ test_optimization }}/{{ test_configuration }}/latency/{{ test_protocol }}-mtu-{{ test_mtu }}-{{ item[0] }}.log"
        test_mtu: "1500"
        test_hostname: "doktnet01"
        test_protocol: "{{ item[1] }}"
        test_env: "{{ test_environment }}"
        kubeconfig: "../../kubeconfig"
      with_nested: 
        - "{{ range(1,3) }}"
        - "{{ protocols }}"
      tags: ['test-latency','mtu-1500']

    - name: Set MTU
      shell: "sudo ip link set dev {{ item }} mtu 9000"
      with_items: 
        - "{{ test_devices }}"
      ignore_errors: true
      tags: ['set-mtu']

    - include_tasks: "../../tests/test_bandwith.yml"
      vars: 
        test_endpoint: "{{ bandwidth_server }}"
        test_config: "{{ test_configuration }}"
        test_optim: "{{ test_optimization }}"
        test_port: "30080"
        test_packet_size: "{{ item[1] }}"
        test_duration: "30"
        test_log_output: "/testing_results/{{ test_optimization }}/{{ test_configuration }}/bandwith/{{ test_protocol }}-mtu-{{ test_mtu }}-packet-{{ test_packet_size }}-{{ item[0] }}.log"
        test_mtu: "9000"
        test_hostname: "doktnet01"
        test_protocol: "{{ item[2] }}"
        test_env: "{{ test_environment }}"
        kubeconfig: "../../kubeconfig"
      with_nested: 
        - "{{ range(1,3) }}"
        - "{{ packet_sizes }}"
        - "{{ protocols }}"
      tags: ['test-bandwith','mtu-9000']

    - include_tasks: "../../tests/test_latency.yml"
      vars: 
        test_endpoint: "{{ latency_server }}"
        test_config: "{{ test_configuration }}"
        test_optim: "{{ test_optimization }}"
        test_duration: "30"
        test_log_output: "/testing_results/{{ test_optimization }}/{{ test_configuration }}/latency/{{ test_protocol }}-mtu-{{ test_mtu }}-{{ item[0] }}.log"
        test_mtu: "9000"
        test_hostname: "doktnet01"
        test_protocol: "{{ item[1] }}"
        test_env: "{{ test_environment }}"
        kubeconfig: "../../kubeconfig"
      with_nested: 
        - "{{ range(1,3) }}"
        - "{{ protocols }}"
      tags: ['test-latency','mtu-9000']