---
- name: Loading necessary kernel modules
  hosts: all
  tasks: 
    - name: Load bridge netfilter kernel module
      modprobe: 
        name: br_netfilter
        state: present

    - name: Allow IPtables to see bridged traffic
      sysctl: 
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present

    - name: Allow ip forwarding 
      sysctl: 
        name: net.ipv4.ip_forward
        value: 1
        state: present
