---
- name: Setting up kubeconfig
  hosts: k8s-control-nodes
  tasks: 
    - name: Fetch kubeconfig
      fetch: 
        src: "/etc/kubernetes/admin.conf"
        dest: "../kubeconfig"
        flat: yes
