---
- name: Setting up environment before executing tuned latency-performance profile tests
  hosts: all
  tasks: 
    - name: Print all changes made in this setup scripts
      debug: 
        msg: "Setting up tuned latency-performance profile tests"

    - name: Activate latency-performance profile
      shell: "sudo tuned-adm profile latency-performance"