---
- name: Cleaning up environment before executing tuned network-latency profile tests
  hosts: all
  tasks: 
    - name: Print all changes made in this setup scripts
      debug: 
        msg: "Cleaning up tuned network-latency profile tests"

    - name: Activate balanced profile
      shell: "sudo tuned-adm profile balanced"